#!/bin/bash
function add_dropbox_host(){
    path=`dirname $0`
    cp /etc/hosts hosts
    cat $path/dropbox.host >> hosts
    sudo cp hosts /etc/hosts
    rm -f hosts
}

function install_dropbox(){
    sudo dpkg -i 'https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_1.4.0_i386.deb'
}

function start_dropbox(){
    dropbox start -i
}

grep '## dropbox ##' /etc/hosts > /dev/null || add_dropbox_host
install_dropbox && start_dropbox
