#!/bin/bash
function install_ruby(){
  prepair_lib
  install_rvm
  rvm install 1.9.3
  rvm use 1.9.3 --default
}

function prepair_lib(){
  sudo apt-get install build-essential openssl libreadline6 libreadline6-dev curl \
                       git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 \
                       libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf \
                       libc6-dev ncurses-dev automake libtool bison subversion
}

function install_rvm(){
  which rvm || (curl -L https://get.rvm.io | bash -s stable --ruby && source $HOME/.rvm/scripts/rvm) && echo 'source ~/.rvm/scripts/rvm' >> $HOME/.profile
}

install_ruby
