#!/bin/bash
sudo apt-get install git -y

git config --global user.name qhwa
git config --global user.email qhwa@163.com
git config --global diff.external ~/cmd/diffwrap-meld.sh
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --"
